// 由 scripts/generate-manifest.ts 在 build 时自动生成，请勿手动编辑。

export const commandToGroup: Record<string, string> = {
  "getAlphaConfig": "init",
  "initAlpha": "init",
  "devopsScene": "scene",
  "healthHealthPing": "root",
  "login": "root",
  "logout": "root",
  "testApi": "root",
  "uid": "root",
  "userinfo": "root",
  "ciAppSync": "ci",
  "ciBranchList": "ci",
  "ciBranchSearch": "ci",
  "ciBuildCancel": "ci",
  "ciBuildFind": "ci",
  "ciBuildFreedomBuild": "ci",
  "ciBuildFreedomTags": "ci",
  "ciBuildGetBuild": "ci",
  "ciBuildGetLatest": "ci",
  "ciBuildGetSelfBuild": "ci",
  "ciBuildList": "ci",
  "ciBuildManualProcess": "ci",
  "ciBuildParamsBuild": "ci",
  "ciBuildPopularList": "ci",
  "ciBuildRecent": "ci",
  "ciBuildWait": "ci",
  "ciInfoChangeInfo": "ci",
  "ciInfoGetRelCommit": "ci",
  "ciInfoGetServerTime": "ci",
  "ciInfoJenkinsOutput": "ci",
  "ciManageClearCache": "ci",
  "ciManageGetConfig": "ci",
  "ciManageGetPipelines": "ci",
  "ciManageGetTemplateList": "ci",
  "ciManageResetVersion": "ci",
  "ciManageSetConfig": "ci",
  "ciManageSyncCiConfig": "ci",
  "ciManageUpdateConfig": "ci",
  "ciRepoAdd": "ci",
  "ciRepoConfigDetail": "ci",
  "ciRepoInfo": "ci",
  "ciRepoList": "ci",
  "ciRepoPage": "ci",
  "deployAppsAzDeploy": "deploy",
  "deployAppsBashUrl": "deploy",
  "deployAppsDetailK8s": "deploy",
  "deployAppsImageVersion": "deploy",
  "deployAppsInstall": "deploy",
  "deployAppsLogUrl": "deploy",
  "deployAppsNsList": "deploy",
  "deployAppsPage": "deploy",
  "deployAppsRecentList": "deploy",
  "deployAppsRefreshResource": "deploy",
  "deployAppsRollback": "deploy",
  "deployAppsSync": "deploy",
  "deployAppsUninstall": "deploy",
  "deployAppsUpgrade": "deploy",
  "deployAppsVersionList": "deploy",
  "deployAppsViewHistory": "deploy",
  "deployAppsViewK8s": "deploy",
  "deployChartsDeployStatus": "deploy",
  "deployChartsDetail": "deploy",
  "deployChartsPage": "deploy",
  "deployChartsValues": "deploy",
  "deployChartsVersion": "deploy",
  "deployClusterAdd": "deploy",
  "deployClusterDestinations": "deploy",
  "deployClusterDetail": "deploy",
  "deployClusterEdit": "deploy",
  "deployClusterList": "deploy",
  "deployClusterPage": "deploy",
  "deployClusterTypeList": "deploy",
  "deployMaterialAdd": "deploy",
  "deployMaterialDetail": "deploy",
  "deployMaterialEdit": "deploy",
  "deployMaterialList": "deploy",
  "deployMaterialPage": "deploy",
  "deployMaterialSync": "deploy",
  "deployMaterialUpload": "deploy",
  "deployProjectAzDeploy": "deploy",
  "deployProjectAzProjectAdd": "deploy",
  "deployProjectAzProList": "deploy",
  "deployProjectAzUserList": "deploy",
  "deployProjectDeploy": "deploy",
  "deployProjectDeployPage": "deploy",
  "deployProjectDeployPageExpand": "deploy",
  "deployProjectFilePush": "deploy",
  "deployProjectPush": "deploy",
  "deployProjectPushGoon": "deploy",
  "deployProjectPushList": "deploy",
  "deployProjectPushPage": "deploy",
  "deployProjectPushPageExpand": "deploy",
  "deployProjectRetryAzDeploy": "deploy",
  "deployProjectRetryDeploy": "deploy",
  "deployPushenvAdd": "deploy",
  "deployPushenvDetail": "deploy",
  "deployPushenvEdit": "deploy",
  "deployPushenvList": "deploy",
  "deployPushenvPage": "deploy",
  "fileMetadataAdd": "file",
  "fileMetadataDownload": "file",
  "fileMetadataPage": "file",
  "fileMetadataPreview": "file",
  "fileMetadataTypes": "file",
  "iterGetTree": "iter",
  "iterHotfixDetail": "iter",
  "iterHotfixList": "iter",
  "iterHotfixMerge": "iter",
  "iterHotfixSave": "iter",
  "iterProdAdd": "iter",
  "iterProdGetList": "iter",
  "iterProjectAdd": "iter",
  "iterProjectDelete": "iter",
  "iterProjectGetList": "iter",
  "iterVersionAdd": "iter",
  "iterVersionDelete": "iter",
  "iterVersionDetail": "iter",
  "iterVersionDisable": "iter",
  "iterVersionEdit": "iter",
  "iterVersionGetRecentTestSubmitted": "iter",
  "iterVersionGetTree": "iter",
  "iterVersionList": "iter",
  "iterVersionMergeHis": "iter",
  "iterVersionSwitchAz2resourceUrl": "iter",
  "iterVersionSwitchEnvInit2resourceUrl": "iter",
  "iterVersionSwitchGflow2resourceUrl": "iter",
  "iterVersionSwitchUdf2resourceUrl": "iter",
  "iterVersionTagList": "iter",
  "iterVersionTestVersionCount": "iter",
  "iterVersionTestVersionDetail": "iter",
  "iterVersionTestVersionList": "iter",
  "iterVersionTestVersionSave": "iter",
  "iterVersionTestVersionSubmit": "iter",
  "rbacPrivilegeAssignPrivileges": "rbac",
  "rbacPrivilegeCurrentList": "rbac",
  "rbacPrivilegeList": "rbac",
  "rbacRoleAssignRoles": "rbac",
  "rbacRoleCurrentList": "rbac",
  "opsPush": "ops",
  "pushPkg": "push"
};

export const groupCommands: Record<string, string[]> = {
  "init": [
    "getAlphaConfig",
    "initAlpha"
  ],
  "scene": [
    "devopsScene"
  ],
  "root": [
    "healthHealthPing",
    "login",
    "logout",
    "testApi",
    "uid",
    "userinfo"
  ],
  "ci": [
    "ciAppSync",
    "ciBranchList",
    "ciBranchSearch",
    "ciBuildCancel",
    "ciBuildFind",
    "ciBuildFreedomBuild",
    "ciBuildFreedomTags",
    "ciBuildGetBuild",
    "ciBuildGetLatest",
    "ciBuildGetSelfBuild",
    "ciBuildList",
    "ciBuildManualProcess",
    "ciBuildParamsBuild",
    "ciBuildPopularList",
    "ciBuildRecent",
    "ciBuildWait",
    "ciInfoChangeInfo",
    "ciInfoGetRelCommit",
    "ciInfoGetServerTime",
    "ciInfoJenkinsOutput",
    "ciManageClearCache",
    "ciManageGetConfig",
    "ciManageGetPipelines",
    "ciManageGetTemplateList",
    "ciManageResetVersion",
    "ciManageSetConfig",
    "ciManageSyncCiConfig",
    "ciManageUpdateConfig",
    "ciRepoAdd",
    "ciRepoConfigDetail",
    "ciRepoInfo",
    "ciRepoList",
    "ciRepoPage"
  ],
  "deploy": [
    "deployAppsAzDeploy",
    "deployAppsBashUrl",
    "deployAppsDetailK8s",
    "deployAppsImageVersion",
    "deployAppsInstall",
    "deployAppsLogUrl",
    "deployAppsNsList",
    "deployAppsPage",
    "deployAppsRecentList",
    "deployAppsRefreshResource",
    "deployAppsRollback",
    "deployAppsSync",
    "deployAppsUninstall",
    "deployAppsUpgrade",
    "deployAppsVersionList",
    "deployAppsViewHistory",
    "deployAppsViewK8s",
    "deployChartsDeployStatus",
    "deployChartsDetail",
    "deployChartsPage",
    "deployChartsValues",
    "deployChartsVersion",
    "deployClusterAdd",
    "deployClusterDestinations",
    "deployClusterDetail",
    "deployClusterEdit",
    "deployClusterList",
    "deployClusterPage",
    "deployClusterTypeList",
    "deployMaterialAdd",
    "deployMaterialDetail",
    "deployMaterialEdit",
    "deployMaterialList",
    "deployMaterialPage",
    "deployMaterialSync",
    "deployMaterialUpload",
    "deployProjectAzDeploy",
    "deployProjectAzProjectAdd",
    "deployProjectAzProList",
    "deployProjectAzUserList",
    "deployProjectDeploy",
    "deployProjectDeployPage",
    "deployProjectDeployPageExpand",
    "deployProjectFilePush",
    "deployProjectPush",
    "deployProjectPushGoon",
    "deployProjectPushList",
    "deployProjectPushPage",
    "deployProjectPushPageExpand",
    "deployProjectRetryAzDeploy",
    "deployProjectRetryDeploy",
    "deployPushenvAdd",
    "deployPushenvDetail",
    "deployPushenvEdit",
    "deployPushenvList",
    "deployPushenvPage"
  ],
  "file": [
    "fileMetadataAdd",
    "fileMetadataDownload",
    "fileMetadataPage",
    "fileMetadataPreview",
    "fileMetadataTypes"
  ],
  "iter": [
    "iterGetTree",
    "iterHotfixDetail",
    "iterHotfixList",
    "iterHotfixMerge",
    "iterHotfixSave",
    "iterProdAdd",
    "iterProdGetList",
    "iterProjectAdd",
    "iterProjectDelete",
    "iterProjectGetList",
    "iterVersionAdd",
    "iterVersionDelete",
    "iterVersionDetail",
    "iterVersionDisable",
    "iterVersionEdit",
    "iterVersionGetRecentTestSubmitted",
    "iterVersionGetTree",
    "iterVersionList",
    "iterVersionMergeHis",
    "iterVersionSwitchAz2resourceUrl",
    "iterVersionSwitchEnvInit2resourceUrl",
    "iterVersionSwitchGflow2resourceUrl",
    "iterVersionSwitchUdf2resourceUrl",
    "iterVersionTagList",
    "iterVersionTestVersionCount",
    "iterVersionTestVersionDetail",
    "iterVersionTestVersionList",
    "iterVersionTestVersionSave",
    "iterVersionTestVersionSubmit"
  ],
  "rbac": [
    "rbacPrivilegeAssignPrivileges",
    "rbacPrivilegeCurrentList",
    "rbacPrivilegeList",
    "rbacRoleAssignRoles",
    "rbacRoleCurrentList"
  ],
  "ops": [
    "opsPush"
  ],
  "push": [
    "pushPkg"
  ]
};
